# Site settings
title: La voragine
description: |
  LaVoragine.org es un laboratorio de edición digital.

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

about_title: Nosotros
projects_title: Home

# User settings
user_description_appendix: |
  Este sitio es un laboratorio: probamos cosas y te explicamos como nos fue. Nuestro tema es la edición digital. Open source, accesible & libre. Este sitio fue construido en [Jekyll][jekyll], y está alojado en [GitHub Pages][gh-pages]. Es *open source*, así que, si te gusta, te invitamos a ir a nuestro repo en [GitHub][github] o hacer un fork para crear tu propia versión.

  [github]: https://github.com/nastarovia
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


email: info@lavoragine.org
linkedin: nastarovia
github: nastarovia

relevant_tags: ['Proyectos', 'Edicion digital', 'Blog']

author: la Vorágine
author_title: Un laboratorio de edición digital, open source & accesible
author_photo: logo.png
user_description_short: |
  Este sitio es un laboratorio: probamos cosas y te explicamos como nos fue. Nuestro tema es la edición digital. Open source, accesible & libre.
# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
